name = "tech-temple"
type = "javascript"
pages_build_output_dir = ".next"

# For local testing only
main = "wrangler.js"
compatibility_date = "2026-07-08"

[env.production]
route = "tech-temple.com/*"
zone_id = ""
